-- Crear esquema
CREATE SCHEMA IF NOT EXISTS ENTPS_DATA;

-- Crear tabla Empresa
CREATE TABLE IF NOT EXISTS ENTPS_DATA.EMPRESAS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CUIT VARCHAR(20) UNIQUE NOT NULL,
    RAZON_SOCIAL VARCHAR(255),
    FECHA_ADHESION DATE,
    CREATED_DATE DATE,
    MODIFIED_DATE DATE,
    CREATED_BY VARCHAR(255),
    MODIFIED_BY VARCHAR(255),
    IS_ACTIVE BOOLEAN
);

-- Insertar datos iniciales
INSERT INTO ENTPS_DATA.EMPRESAS (CUIT, RAZON_SOCIAL, FECHA_ADHESION, CREATED_DATE, MODIFIED_DATE, CREATED_BY, MODIFIED_BY, IS_ACTIVE)
VALUES ('30-11111111-1', 'Empresa A', '2025-02-01', '2025-02-01', '2025-02-02', 'SYSTEM', 'SYSTEM', TRUE);
INSERT INTO ENTPS_DATA.EMPRESAS (CUIT, RAZON_SOCIAL, FECHA_ADHESION, CREATED_DATE, MODIFIED_DATE, CREATED_BY, MODIFIED_BY, IS_ACTIVE)
VALUES ('30-22222222-2', 'Empresa B', '2025-03-01', '2025-03-01', '2025-03-02', 'SYSTEM', 'SYSTEM', TRUE);

-- Crear tabla Transferencia
CREATE TABLE IF NOT EXISTS ENTPS_DATA.TRANSFERENCIAS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    IMPORTE DOUBLE,
    CUENTA_DEBITO VARCHAR(50),
    CUENTA_CREDITO VARCHAR(50),
    EMPRESA_CUIT VARCHAR(20),
    CREATED_DATE DATE,
    MODIFIED_DATE DATE,
    CREATED_BY VARCHAR(255),
    MODIFIED_BY VARCHAR(255),
    IS_ACTIVE BOOLEAN,
    FOREIGN KEY (EMPRESA_CUIT) REFERENCES ENTPS_DATA.EMPRESAS(CUIT)
);

-- Insertar datos iniciales
INSERT INTO ENTPS_DATA.TRANSFERENCIAS (IMPORTE, CUENTA_DEBITO, CUENTA_CREDITO, EMPRESA_CUIT, CREATED_DATE, MODIFIED_DATE, CREATED_BY, MODIFIED_BY, IS_ACTIVE)
VALUES (1000.0, '123-456', '789-012', '30-11111111-1', '2025-02-01', '2025-02-02', 'SYSTEM', 'SYSTEM', TRUE);
INSERT INTO ENTPS_DATA.TRANSFERENCIAS (IMPORTE, CUENTA_DEBITO, CUENTA_CREDITO, EMPRESA_CUIT, CREATED_DATE, MODIFIED_DATE, CREATED_BY, MODIFIED_BY, IS_ACTIVE)
VALUES (2000.0, '234-567', '890-123', '30-22222222-2', '2025-03-01', '2025-03-02', 'SYSTEM', 'SYSTEM', TRUE);
